// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIdwlVvqNkcE-kGHwhn_MDTD1G7Asbbkc',
    appId: '1:307349870313:web:2da6b7150755d401860278',
    messagingSenderId: '307349870313',
    projectId: 'apk-pmr-c878a',
    authDomain: 'apk-pmr-c878a.firebaseapp.com',
    storageBucket: 'apk-pmr-c878a.firebasestorage.app',
    measurementId: 'G-F22BG7PPRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmfd8d7FTv4JMfc_iYf03qIXIl3BeFUzA',
    appId: '1:307349870313:android:8813d344f617d412860278',
    messagingSenderId: '307349870313',
    projectId: 'apk-pmr-c878a',
    storageBucket: 'apk-pmr-c878a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAowDuU_UcOSfFQg2GG4R8P0CdI_A7XP7c',
    appId: '1:307349870313:ios:d27b03952484b98e860278',
    messagingSenderId: '307349870313',
    projectId: 'apk-pmr-c878a',
    storageBucket: 'apk-pmr-c878a.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAowDuU_UcOSfFQg2GG4R8P0CdI_A7XP7c',
    appId: '1:307349870313:ios:d27b03952484b98e860278',
    messagingSenderId: '307349870313',
    projectId: 'apk-pmr-c878a',
    storageBucket: 'apk-pmr-c878a.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIdwlVvqNkcE-kGHwhn_MDTD1G7Asbbkc',
    appId: '1:307349870313:web:1822005f564ed765860278',
    messagingSenderId: '307349870313',
    projectId: 'apk-pmr-c878a',
    authDomain: 'apk-pmr-c878a.firebaseapp.com',
    storageBucket: 'apk-pmr-c878a.firebasestorage.app',
    measurementId: 'G-LEB68J2JBS',
  );
}
